export class AppLayout {
  static readonly STATUS_BAR_HEIGHT: number = 32;
  static readonly BOTTOM_SAFE_HEIGHT: number = 28;
  static readonly FLOATING_TAB_BOTTOM: number = 28;
  static readonly CHAT_LIST_HEADER_EXPANDED: number = 132;
  static readonly CHAT_LIST_HEADER_COLLAPSED: number = 88;
  static readonly CHAT_COMPOSER_HEIGHT: number = 44;
  static readonly CHAT_COMPOSER_SIDE_PADDING: number = 25;
  static readonly SECONDARY_TOP_CONTENT_HEIGHT: number = 86;
  static readonly SECONDARY_TOP_CONTROL_Y_OFFSET: number = 8;
  static readonly TOP_GRADIENT_BLUR_RADIUS: number = 50;
}
